apiVersion: v1
kind: Secret
metadata:
  name: ce-nextgen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ce-nextgen.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "ce-nextgen.generateSecrets" . }}
---
{{- if not .Values.workloadIdentity.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ceng-secret-mount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ce-nextgen.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "ce-nextgen.generateMountSecrets" . }}
{{- end }}