apiVersion: v1
kind: Service
metadata:
  name: ce-nextgen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ce-nextgen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ce-nextgen.selectorLabels" . | nindent 4 }}